# Generated by Django 5.2.3 on 2025-07-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='genero_musical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
