# Generated by Django 5.2.3 on 2025-07-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0002_alter_artista_genero_musical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('fecha_lanzamiento', models.DateField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='mi_trabajo_final.artista')),
            ],
        ),
    ]
