# Generated by Django 5.2.3 on 2025-07-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0005_canciones_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canciones',
            name='usuario',
        ),
    ]
