# Generated by Django 5.2.3 on 2025-07-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0007_canciones_suario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canciones',
            old_name='suario',
            new_name='usuario',
        ),
    ]
