# Generated by Django 5.2.3 on 2025-07-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0008_rename_suario_canciones_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_artistas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
