# Generated by Django 5.2.3 on 2025-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_trabajo_final', '0009_artista_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('fecha_de_lanzamiento', models.DateField()),
            ],
        ),
    ]
